### ISSUE TITLE
PersonalData can't be deleted

### ISSUE THREAD

**Issue by dvayanu** [anotheria/portalkit#37]
When trying to delete personal data:
230728231 2024-07-25 04:30:01,825 WARN  Deletion - Can't delete from PersonalDataDeletionAdapter
java.lang.IllegalArgumentException: invalid hexadecimal representation of an ObjectId: [fd23e687-f199-460a-9cd2-a5dca6bba48f]
	at org.bson.types.ObjectId.parseHexString(ObjectId.java:363)
	at org.bson.types.ObjectId.<init>(ObjectId.java:190)
	at net.anotheria.portalkit.services.personaldata.PersonalDataServiceImpl.delete(PersonalDataServiceImpl.java:102)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.anotheria.moskito.core.predefined.ServiceStatsCallHandler.invoke(ServiceStatsCallHandler.java:115)
	at net.anotheria.moskito.core.dynamic.MoskitoInvokationProxy.invoke(MoskitoInvokationProxy.java:194)
	at jdk.proxy2/jdk.proxy2.$Proxy83.delete(Unknown Source)
	at net.anotheria.portalkit.services.personaldata.generated.RemotePersonalDataServiceSkeleton.delete(RemotePersonalDataServiceSkeleton.java:261)

**Comment by dvayanu** [comment]
release 4.0.5 https://github.com/anotheria/portalkit/releases/tag/portalkit-4.0.5
